/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Cart = Array<CartItem>;
export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Order {
  'status' : OrderStatus,
  'total' : bigint,
  'orderId' : bigint,
  'timestamp' : bigint,
  'buyer' : Principal,
  'items' : Array<CartItem>,
  'buyerInfo' : {
    'name' : string,
    'email' : string,
    'address' : string,
    'phone' : string,
  },
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : bigint,
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeStore' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [
      {
        'name' : string,
        'email' : string,
        'address' : string,
        'phone' : string,
      },
    ],
    bigint
  >,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];